### ISSUE TITLE
question about recursive rule

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#28]
by "recursive rule" I mean a rule with other rules in it's antecedent and/or consequent.

in this simple example : 

```
{?P :subPropertyOf ?Q } => { {_:S ?P _:O} => {_:S ?Q _:O} } .
:k1 :subPropertyOf :k0.
:x :k1 :y.
```

And run` eye --pass-only-new --nope ./test.n3`
I expected to get :
```
:x :k0 :y.
{?U_0 :k1 ?U_1} => {?U_0 :k0 ?U_1}.

```
But only got :
```
{?U_0 :k1 ?U_1} => {?U_0 :k0 ?U_1}.

```
I also tried to write the recursive rule like this:
`{?P :subPropertyOf ?Q } => {@forAll :S, :O. {:S ?P :O} => {:S ?Q :O} } .`
And got the similar result.

Is this a bug or did I make a mistake?

**Comment by josd** [comment]
Thanks for your observation, it was indeed a bug which is fixed in https://github.com/josd/eye/releases/tag/v21.1226.2106
Now you should indeed get
```
{?U_0 :k1 ?U_1} => {?U_0 :k0 ?U_1}.
:x :k0 :y.
```

**Comment by blackwint3r** [comment]
Thank you! Now I indeed get the expected result in the first case.

But in the second case(using keyword `@forAll`) still don't work (it works in CWM, give me expected result). 
Is this syntax has been deprecated？

**Comment by blackwint3r** [comment]
I have also noticed that the keyword `@forAll `seems to be working correctly in EYE when it is inside the antecedent of a recursive rule, for example:
```
{@forAll :a,:b. {:a ?p :b} => {:b :type ?c}} => {?p :range ?c} .
{?a :eat ?b} => {?b :type :food}.
```
give me expected result:
`:eat :range :food.`
But not correct when it is inside the consequent of a recursive rule.

**Comment by josd** [comment]
Thanks again and `@forAll` is now fixed in https://github.com/josd/eye/releases/tag/v21.1227.1119
```
{?P :sup-key- ?Q } => {@forAll :S, :O. {:S ?P :O} => {:S ?Q :O} } .
:k1 :sup-key- :k0.
:x :k1 :y.
```
should now give
```
{?U_0 :k1 ?U_1} => {?U_0 :k0 ?U_1}.
:x :k0 :y.
```

**Comment by blackwint3r** [comment]
👍
